### ISSUE TITLE
Cannot be used normally on brave

### ISSUE THREAD

**Issue by bigface1989** [MichaelYuhe/ai-group-tabs#16]
It doesn't work at all. When you open a new tab, it's still a different color. For example, the BBC, CNN, etc. have been classified as news, but news like Bloomberg is still a different color.

**Comment by MichaelYuhe** [comment]
Does your api key support gpt-4 ?

**Comment by bigface1989** [comment]
> Does your api key support gpt-4?

No, mine is the 3.5 key. Nothing happens after I enter the key. I don’t know if I entered it correctly.

**Comment by MichaelYuhe** [comment]
> > Does your api key support gpt-4?
> 
> No, mine is the 3.5 key. Nothing happens after I enter the key. I don’t know if I entered it correctly.

I've specified the model to gpt-4 by default. You can change it in options page. (You need to download and build for that version now, I'll publish a new version later with other features.

**Comment by MichaelYuhe** [comment]
The new version is published, you can have a try by updating the model in options page now
