### ISSUE TITLE
TypeError in Event Handler on Chrome Extension Post-Update

### ISSUE THREAD

**Issue by Tutu-Shi** [MichaelYuhe/ai-group-tabs#17]
After a recent update, I encountered the following error in a Chrome extension:
`Error in event handler: TypeError: Cannot read properties of undefined (reading '0') at chrome-extension://mjfblbggcgffnijgopjiocacoajgnjak/service_worker.js:1:277 at Array.forEach (<anonymous>) at chrome-extension://mjfblbggcgffnijgopjiocacoajgnjak/service_worker.js:1:259`

**Comment by MichaelYuhe** [comment]
I see, I updated the model to gpt-4 so some users are getting this error because they only have key for 3.5
I will add a feature for selecting model

**Comment by MichaelYuhe** [comment]
You can change the model and API server in options page now.
