### ISSUE TITLE
Add config for API Server

### ISSUE THREAD

**Issue by guohanli** [MichaelYuhe/ai-group-tabs#18]
Can you add a configuration for the API Server address? So that we can use some third-party OpenAI API proxy services.

**Comment by guohanli** [comment]
Yes, that would be very helpful. Thank you.

**Comment by kvinwang** [comment]
And nice to have the choice of models, such as the cheaper GPT-3.5 or the advanced GPT-4 Turbo. It allows users to select the model that best fits their needs.

**Comment by MichaelYuhe** [comment]
Yes I'll support this as well

**Comment by MichaelYuhe** [comment]
You can change the model and API server in options page now.
