### ISSUE TITLE
There is no option for custom model and api server

### ISSUE THREAD

**Issue by nohzafk** [MichaelYuhe/ai-group-tabs#19]
<img width="386" alt="image" src="https://github.com/MichaelYuhe/ai-group-tabs/assets/149959021/993d70c4-7b47-4cae-87e1-e9a665fffca4">

i read #18 but can't find any options

i am using latest chrome and extension release 0.0.4

**Comment by MichaelYuhe** [comment]
You need to open Options page from the extension list

**Comment by nohzafk** [comment]
thanks
