### ISSUE TITLE
Automatic grouping existing tabs should be default.

### ISSUE THREAD

**Issue by FledgeXu** [MichaelYuhe/ai-group-tabs#27]
For example:
<img width="219" alt="image" src="https://github.com/MichaelYuhe/ai-group-tabs/assets/16664654/cecef5bb-2a3c-4cf3-bd50-7dad688e9329">

`Instagram` should join the existed tab group "Social Media" instead of creating a new one.

**Comment by FledgeXu** [comment]
This Bug seems to only exist in GPT 3.5 model…

**Comment by MichaelYuhe** [comment]
Fixed in the latest version, I'll release it today.
