### ISSUE TITLE
Feature: Missing hints.

### ISSUE THREAD

**Issue by FledgeXu** [MichaelYuhe/ai-group-tabs#29]
<img width="361" alt="image" src="https://github.com/MichaelYuhe/ai-group-tabs/assets/16664654/fcd9bb1d-117f-4946-ab6e-b75f21995fcd">

It would be nice if there are some hints about this input box.

**Comment by MichaelYuhe** [comment]
Yes I think we need a placeholder, would you like to do this?

**Comment by MichaelYuhe** [comment]
Closed by @lawvs
