### ISSUE TITLE
[feature request]: Add filtering options, some URLs do not need to be included in the grouping strategy.

### ISSUE THREAD

**Issue by hqwuzhaoyi** [MichaelYuhe/ai-group-tabs#60]
I think that in daily scenarios, not all tags need to be uploaded, it may be personal needs or privacy requirements.

Does this feature need to be added to the project? I also want to try adding it.😃

**Comment by MichaelYuhe** [comment]
Yes I'd love to see this feature! Maybe we can let user set a filter rule in options page.
For example, a textarea input in Options page, user can set filter rules by prefix, like github.com

**Comment by MichaelYuhe** [comment]
And I just assigned this issue to you, looking forward to your work!

**Comment by hqwuzhaoyi** [comment]
> And I just assigned this issue to you, looking forward to your work!我刚刚把这个问题交给了你，期待你的工作！

Thank you very much for your trust. I will provide a version as soon as possible.😆

**Comment by hqwuzhaoyi** [comment]
> And I just assigned this issue to you, looking forward to your work!

Do you think it's more suitable to add it on the Setting page or inside a popup?🤔

**Comment by MichaelYuhe** [comment]
> > And I just assigned this issue to you, looking forward to your work!
> 
> Do you think it's more suitable to add it on the Setting page or inside a popup?🤔

I think it's better in the options page. Or we need to use tabs in popup so that it won't mess up with too much content

**Comment by hqwuzhaoyi** [comment]
I also think it might be more suitable to put it in a popup😁, because there may be a need for a lot of configuration, which would appear too crowded inside the popup.🤔

I will first try to add it to the options page.👍

**Comment by hqwuzhaoyi** [comment]
How does this look? Imitating the logic of Surge's rule, if a rule is matched, GPT requests will not be made.@MichaelYuhe 
![CleanShot 2023-12-12 at 15 32 35](https://github.com/MichaelYuhe/ai-group-tabs/assets/44605072/24d2f473-a96d-4a75-a5e4-6e7d289b8711)
![CleanShot 2023-12-12 at 15 30 40](https://github.com/MichaelYuhe/ai-group-tabs/assets/44605072/b1514d67-db80-48e7-930e-ce97aa37e1a3)

**Comment by MichaelYuhe** [comment]
I think we don't need to use the keyword rule? I think it's much better to be like this one below ⬇️
<img width="556" alt="image" src="https://github.com/MichaelYuhe/ai-group-tabs/assets/63531512/78eaad7d-b640-4747-a377-11a53e62f954">
What do u think of it? Discussions are welcome!

**Comment by hqwuzhaoyi** [comment]
> I think we don't need to use the keyword rule? I think it's much better to be like this one below ⬇️ <img alt="image" width="556" src="https://private-user-images.githubusercontent.com/63531512/289782079-78eaad7d-b640-4747-a377-11a53e62f954.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjc4OTksIm5iZiI6MTcwMjM2NzU5OSwicGF0aCI6Ii82MzUzMTUxMi8yODk3ODIwNzktNzhlYWFkN2QtYjY0MC00NzQ3LWEzNzctMTFhNTNlNjJmOTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA3NTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZmFmNjFlYWYwYzM1OTgxMmQ0YTY0ZjAyZjNlY2I1OGUxNThjNzQwNGIwYzUxYjMxNTAyOGZmZmM0OTMyYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9rsvdpW_R2OBPBFkY5JJqTHSUyEVztjUxU_HVS1pvNM"> What do u think of it? Discussions are welcome!

😄At first, my idea was to use regular expressions for matching, but the complexity of regular expressions is relatively high. 

Although there are many types of rules in Surge, the difficulty of understanding will be lower. Here are some specific examples of these three types.

![CleanShot 2023-12-12 at 15 57 47](https://github.com/MichaelYuhe/ai-group-tabs/assets/44605072/d7d36255-f6ce-4ab2-b091-fbaa91b3dc2c)

I think we can also treat regular expressions as a type and add them, so the adaptability will be higher.

In this way, we have four types to judge.😆

**Comment by MichaelYuhe** [comment]
Yes your solution is much eaiser to use. But I think maybe using 'prefix' is much better than 'suffix'?

**Comment by hqwuzhaoyi** [comment]
> Yes your solution is much eaiser to use. But I think maybe using 'prefix' is much better than 'suffix'?

Because now DOMAIN actually uses URL host for filtering, just like this

```
function matchesRule(host: string, rule: FilterRuleItem) {
  const { type, rule: value } = rule;
  switch (type) {
    case "DOMAIN":
      // Exact match; example.com should match example.com
      return host === value;
    case "DOMAIN-SUFFIX":
      // Suffix matching; example.com should match www.example.com
      return host.endsWith("." + value) || host === value;
    case "DOMAIN-KEYWORD":
      // Keyword matching; example should match www.example.com
      return host.includes(value);
    default:
      // If the rule type is unknown, return false
      return false;
  }
}
```

But what is matched using the suffix?🤔

**Comment by hqwuzhaoyi** [comment]
@MichaelYuhe The existing code has been submitted first. If you have more suggestions, please feel free to point them out.😆
