### ISSUE TITLE
分组效果不好

### ISSUE THREAD

**Issue by SpecialYang** [MichaelYuhe/ai-group-tabs#66]
用的release的最新版本。

1. 不会自动分组
2. 需要多刷新几次
3. 不会自动学习，根域名一致时不会自动合并
4. 即使域名一致，不同path也不会自动合并
5. 标签页里右键添加的分组，在扩展插件里不展示，不知道是这两块本来就有区别吗？

不知道是不是我使用姿势不对，都是需要手动添加分组里。

**Comment by SpecialYang** [comment]
![image](https://github.com/MichaelYuhe/ai-group-tabs/assets/33012260/0860bdda-bcbe-4a14-850b-4f1466fe7ca5)

刷新里好几次，这个github页面也进不去左边的分组。

**Comment by MichaelYuhe** [comment]
可能是网络环境问题，导致请求很慢；
目前没有做域名分组；
目前没有做上下文和自动学习，直接调用的 OpenAI API ；

**Comment by SpecialYang** [comment]
多谢回答，看看第五个问题呢

**Comment by MichaelYuhe** [comment]
> 5\. 标签页里右键添加的分组，在扩展插件里不展示，不知道是这两块本来就有区别吗？

哦，这一块是我们没有考虑到，因为自己平常没使用过，现在才知道有 =_= 后面支持一下同步

**Comment by MichaelYuhe** [comment]
Closed by #67 due to duplicate
