### ISSUE TITLE
Sync with groups created manually

### ISSUE THREAD

**Issue by MichaelYuhe** [MichaelYuhe/ai-group-tabs#67]
We can create a group manually by right-clicking on the tab. But the extension doesn't record that group now

- Add a new type for new group created manually
- Record in tabGroupMap
- Merge group if there is already a group with that type

**Comment by hqwuzhaoyi** [comment]
In addition to recording the group name, is it necessary to record the behavior of manual or automatic creation?

**Comment by hqwuzhaoyi** [comment]
Is anyone following up on this issue now? I want to go and solve it.

**Comment by MichaelYuhe** [comment]
> Is anyone following up on this issue now? I want to go and solve it.

Just assigned this issue to you. You can check the latest updates on main branch, here is a new variable called tabMap to record all the tabs state manully

**Comment by hqwuzhaoyi** [comment]
When tabGroup be updated, I added logic. At this time, if the configurations saved in title and popup are different, the tabGroup will be stored and synchronized to the configuration of popUp.

And next time when clicking "Group Existing Tabs", it will query all tabsId under tabGroup, then filter them out from the group event after openai.
