### ISSUE TITLE
Unable to automatically name groups

### ISSUE THREAD

**Issue by logicfallacy** [MichaelYuhe/ai-group-tabs#7]
## Environment

1. Browser: Thorium version 116.0.5845.169 (Official version) (arm64)
2. Extension version: Latest version
3. Confirmed that the OpenAI key is working fine
4. Some Group types have been initially set up

## Specific Issue

Try closing the browser, then reopening it and visiting some websites to check if the functionality is working properly. The extension only automatically divides each tab into individual unnamed groups for me, but according to the Surge Dashboard, network requests appear to be successful.

**Comment by MichaelYuhe** [comment]
Thanks for the feedback, I'll investigate this issue later in weekend
