### ISSUE TITLE
[BUG] : System is not checking whether the API key is Valid or not

### ISSUE THREAD

**Issue by Tufailahmed-Bargir** [MichaelYuhe/ai-group-tabs#92]
Description : on the "your openAI API key " it is not checking the key is valid or not.
screenshot:
![image](https://github.com/MichaelYuhe/ai-group-tabs/assets/142114244/60cf5e1b-8b36-48b8-9948-ec7fd34bee5a)
Expeted output : it must check whether the API KEY is valid or not before proceeding..

**Comment by MichaelYuhe** [comment]
When you press the validate what happened? :D

**Comment by Tufailahmed-Bargir** [comment]
for few seconds it started loading and nothing happen

**Comment by MichaelYuhe** [comment]
It will show an icon to show whether it's valid or not

**Comment by MichaelYuhe** [comment]
Fixed
