### ISSUE TITLE
请问能支持Gemini Pro API吗？

### ISSUE THREAD

**Issue by androidcn** [MichaelYuhe/ai-group-tabs#93]
请问能支持Gemini Pro API吗？

**Comment by MichaelYuhe** [comment]
可以的，我找时间支持一下

**Comment by hqwuzhaoyi** [comment]
@MichaelYuhe Is there any progress in development? I'm here to support.

**Comment by MichaelYuhe** [comment]
@hqwuzhaoyi Just assigned this issue to you! Thanks

**Comment by MichaelYuhe** [comment]
Closed by #95

**Comment by androidcn** [comment]
@hqwuzhaoyi Thanks
